### ISSUE TITLE
define new msg

### ISSUE THREAD

**Issue by chaolmu** [chaolmu/flypulator_simulation#1]
is it nessary to define a new msg Vector6dMsg?

**Comment by JinyaoZhu** [comment]
In my opinion, yes, but it doesn't have to be "Vector6dMsg", it might have some other names like "RotorVelocityCommands" or "TeleopCommands". Because it seems that there's no suitable msg type in ROS default msg package such as "geometry_msgs" or "sensor_msgs", to pass the msg from control_plugin to aero_plugin, which is velocity command of the six rotors. Of course, we can use msg with six elements like "twist" or "wrench", but it might seem a bit confusing. In teleop node, which needs to send attitude or position commands to control_plugin, has the same problem. So I think, using custom msg type might make the whole structure more clear and has a better expandability.

**Comment by chaolmu** [comment]
Yes, we should keep it in case for specific msg type. Since it is global valid, I would like move his package to another level. For organisation, I will start another issue.
